options:
    client-port:
        type: int
        default: 4222
        description: A port NATS listens on for incoming client connections.
    cluster-port:
        type: int
        default: 4248
        description: A port NATS listens on for incoming cluster connections.
    listen-on-all-addresses:
        type: boolean
        default: false
        description: |
            Whether to use 0.0.0.0 for the client listening socket or not (all IPv4 and IPv6 addresses).
            NATS does not support multiple "listen" directives and the charm will error out if there are
            cross-model relations that result in multiple *different* bind-addresses available for relations of the
            client relation endpoint.
    tls-key:
        type: string
        default: ""
        description: A TLS server key to be used by NATS.
    tls-cert:
        type: string
        default: ""
        description: A TLS server certificate to be used by NATS.
    tls-ca-cert:
        type: string
        default: ""
        description: |
            A CA certificate to be used for verification of TLS certificates of NATS cluster peers.
            Optional if TLS certificates are signed by a certificate authority that the core snap trusts.
    verify-tls-clients:
        type: boolean
        default: false
        description: Enable or disable mandatory client TLS certificate verification.
    map-tls-clients:
        type: boolean
        default: false
        description: |
            Enable or disable usage of values in client certificates for authentication purposes (used in
            conjunction with verify-tls-clients only.
    debug:
        type: boolean
        default: false
        description: Enable nats-server debug logging.
    trace:
        type: boolean
        default: false
        description: Enable tracing of raw protocol messages for nats-server.
    snap-channel:
        type: string
        default: stable
        description: Snap Store channel to install the NATs snap from
    nagios_context:
      default: "juju"
      type: string
      description: |
        Used by the nrpe subordinate charms.
        A string that will be prepended to instance name to set the host name
        in nagios. So for instance the hostname would be something like:
            juju-myservice-0
        If you're running multiple environments with the same services in them
        this allows you to differentiate between them.
    nagios_servicegroups:
      default: ""
      type: string
      description: |
        A comma-separated list of nagios servicegroups.
        If left empty, the nagios_context will be used as the servicegroup