name: Promote Charms & Bundles

on:
  workflow_call:
    secrets:
      CHARMHUB_TOKEN:
        required: true
    inputs:
      from-risk:
        type: string
        description: 'Charmhub channel risk to promote from'
        default: ''
      to-risk:
        type: string
        description: 'Charmhub channel risk to promote to'
        default: ''

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  promote-charms-and-bundles:
    environment: ${{ contains(inputs.to-risk, 'stable') && 'stable' || null }}
    name: Promote charms
    runs-on: [self-hosted, linux, X64, jammy, large]
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: Install dependencies
      run: |
        sudo apt install  -y zip
        sudo snap install --classic --channel=latest/stable charmcraft
        sudo snap install --channel=3/stable juju
    - name: Promote charms
      env:
        CHARMCRAFT_AUTH: ${{ secrets.CHARMHUB_TOKEN }}
      run: |
        track=latest

        for series in jammy noble ; do
          ./scripts/promote-charms.sh \
            --from="$track"/${{ inputs.from-risk }} \
            --to="$track"/${{ inputs.to-risk }} \
            --series=${series}
        done

