name: Promote new set of beta charms
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  promote-candidate:
    uses: ./.github/workflows/promote-charms.yaml
    with:
      from-risk: edge
      to-risk: beta
    secrets:
      CHARMHUB_TOKEN: ${{ secrets.CHARMHUB_TOKEN }}

