name: Pull Request
on:
  pull_request:
    paths-ignore:
      - ".github/renovate*"
      - ".github/workflows/release.yaml"
      - ".github/workflows/renovate.yaml"
      - ".github/workflows/update-libs.yaml"
      - ".gitignore"
      - ".jujuignore"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yaml
